name: Continuous integration

on:
  pull_request:
  push:
    branches:
      - main
      - "dev*"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10", 3.11]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Update pip and install the package
        run: |
          python -m pip install --upgrade pip
          python -m pip install ".[test]"
      - name: Run tests
        run: |
          python -m pytest tests --cov=sips --cov-fail-under=100
      - name: Install and run linters
        if: matrix.python-version == 3.11
        run: |
          python -m pip install ".[dev]"
          python -m ruff check .
          python -m ruff format --check .
